"""
End-to-end example on SauceDemo, with the semantic engine.

    python -m anchor.main

1. Opens the browser with a persistent profile (profiles/user_001).
2. If there is no session, waits for the user to log in manually
   (user: standard_user, password: secret_sauce). The password never
   goes through the system.
3. Runs steps described in natural language. When the heuristic is
   not sure, it asks in the terminal; the choices are kept in
   memory/saucedemo.json and are not asked again.

Here the plan (the list of steps) is fixed, to demonstrate the engine
without an LLM. For a text request, with the plan generated by the LLM,
use the agent:
python -m anchor.agent --profile <profile> --url <link> "<request>"

Old version, with fixed selectors, for comparison:
anchor/automation/saucedemo.py
"""

from pathlib import Path

from anchor.browser.browser import close_browser, start_browser
from anchor.browser.session import is_logged_in, wait_for_login
from anchor.engine.action_executor import ActionExecutor
from anchor.engine.disambiguation import TerminalDisambiguator
from anchor.engine.element_resolver import ElementResolver
from anchor.engine.memory import ChoiceMemory
from anchor.i18n import t

PROFILE_PATH = "./profiles/user_001"
URL = "https://www.saucedemo.com/"
LOGGED_IN_SELECTOR = ".inventory_list"
MEMORY = Path("memory") / "saucedemo.json"

# Site-specific vocabulary (kept out of the generic dictionary).
VOCAB = {
    "mochila": "backpack",
    "lanterna": "light",
    "bicicleta": "bike",
    "camiseta": "shirt",
    "jaqueta": "jacket",
}

# The steps are the user's requests, in Portuguese, like the evaluation tasks.
PLAN = [
    ("click", "adicionar a mochila ao carrinho", {}),
    ("click", "adicionar a lanterna de bicicleta ao carrinho", {}),
    ("click", "abrir o carrinho", {}),
]


def run(page) -> list:
    executor = ActionExecutor(
        page,
        resolver=ElementResolver(page, synonyms=VOCAB),
        disambiguator=TerminalDisambiguator(),
        can_point=True,
        memory=ChoiceMemory(MEMORY),
    )

    results = []
    for action, description, kwargs in PLAN:
        result = getattr(executor, action)(description, **kwargs)
        print(t("demo.step", description=description, status=result.status, by=result.resolved_by))
        results.append(result)
        if not result:
            print(t("demo.stopped"))
            break
    return results


def main():
    playwright, context = start_browser(PROFILE_PATH)
    page = context.pages[0] if context.pages else context.new_page()
    page.goto(URL)

    if is_logged_in(page, LOGGED_IN_SELECTOR):
        print(t("session.logged_in"))
    else:
        wait_for_login(page, LOGGED_IN_SELECTOR)

    print(t("demo.starting"))
    run(page)

    input(t("demo.press_enter"))
    close_browser(playwright, context)


if __name__ == "__main__":
    main()
